#!/usr/bin/env node
// generate-brands.js - Run before build to create brand data from logos

const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const logosDir = path.join(rootDir, 'public', 'logos');
const outputFile = path.join(rootDir, 'lib', 'brands-data-generated.ts');

// Category mapping
const categoryMap = {
  'tech-saas': ['google', 'microsoft', 'apple', 'amazon', 'meta', 'netflix', 'spotify', 'airbnb', 'uber', 'lyft', 'twitter', 'slack', 'zoom', 'discord', 'notion', 'figma', 'github', 'gitlab', 'docker', 'kubernetes', 'salesforce', 'oracle', 'sap', 'adobe', 'nvidia', 'intel', 'amd', 'cisco', 'cloudflare'],
  'finance': ['visa', 'mastercard', 'chase', 'bank', 'wells', 'citi', 'goldman', 'morgan', 'blackrock', 'vanguard', 'fidelity', 'paypal', 'stripe', 'square', 'american-express'],
  'retail': ['walmart', 'target', 'costco', 'amazon', 'ebay', 'shopify', 'bestbuy', 'nordstrom', 'macys', 'ikea', 'wayfair'],
  'automotive': ['tesla', 'ford', 'gm', 'chevrolet', 'toyota', 'honda', 'bmw', 'mercedes', 'audi', 'vw', 'volkswagen', 'porsche', 'nissan', 'hyundai', 'kia'],
  'healthcare': ['pfizer', 'moderna', 'johnson', 'novartis', 'roche', 'merck', 'united', 'cvs', 'walgreens', 'pfizer'],
  'entertainment': ['disney', 'netflix', 'warner', 'paramount', 'sony', 'universal', 'spotify', 'hulu', 'hbo'],
  'food-beverage': ['coca', 'pepsi', 'nestle', 'mcdonalds', 'starbucks', 'yum', 'chipotle', 'dominos'],
  'energy': ['exxon', 'chevron', 'shell', 'bp', 'duke', 'southern', 'next-era'],
  'travel': ['delta', 'united', 'american', 'marriott', 'hilton', 'booking', 'airbnb', 'uber', 'lyft'],
  'telecom': ['verizon', 'att', 'tmobile', 'comcast', 'charter'],
};

function getCategory(name) {
  const lower = name.toLowerCase();
  for (const [cat, keywords] of Object.entries(categoryMap)) {
    for (const keyword of keywords) {
      if (lower.includes(keyword)) return cat;
    }
  }
  return 'tech-saas';
}

function generateBrands() {
  if (!fs.existsSync(logosDir)) {
    console.log('Logos directory not found, creating empty brands array');
    return [];
  }

  const files = fs.readdirSync(logosDir);
  const logos = files
    .filter(f => f.endsWith('.png') || f.endsWith('.svg'))
    .map(f => {
      const name = f.replace(/\.png$/, '').replace(/\.svg$/, '');
      const ext = f.endsWith('.png') ? 'png' : 'svg';
      return { name, ext, filename: f };
    });

  console.log(`Found ${logos.length} logos`);

  return logos.map((logo, index) => {
    const displayName = logo.name
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
    
    const category = getCategory(logo.name);
    
    return {
      id: logo.name,
      name: displayName,
      slug: logo.name,
      description: `${displayName} is a leading brand known for its distinctive visual identity and market presence.`,
      categorySlug: category,
      tags: ['brand', 'logo', category],
      logoUrl: `/logos/${logo.filename}`,
      dominantColors: [],
      country: 'US',
      website: `https://${logo.name.replace(/-/g, '')}.com`,
      createdAt: new Date(Date.now() - index * 86400000).toISOString(),
      featured: false,
      views: Math.floor(Math.random() * 1000)
    };
  });
}

const brands = generateBrands();

const fileContent = `// Auto-generated by generate-brands.js - DO NOT EDIT
import { Brand } from './brands-data';

export const generatedBrands: Brand[] = ${JSON.stringify(brands, null, 2)};
`;

fs.writeFileSync(outputFile, fileContent);
console.log(`✅ Generated ${brands.length} brands to ${outputFile}`);
